# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Whit's Daily JSON Upload

on:
  workflow_dispatch:
  schedule:
  - cron: "0 10 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip3 install requests
    - name: Run script, generate today's JSON
      run: python3 /home/runner/work/whits-daily/whits-daily/whits_daily.py
    - name: Upload today's JSON to repo
      run: |
        date > generated.txt
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "generated"
        git push
